// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var concat, gulp, gutil, jshint, minifyCss, minifyHtml, notify, path, pkg, uglify;

  gulp = require('gulp');

  concat = require('gulp-concat');

  gutil = require('gulp-util');

  uglify = require('gulp-uglify');

  jshint = require('gulp-jshint');

  notify = require('gulp-notify');

  minifyCss = require('gulp-minify-css');

  minifyHtml = require('gulp-minify-html');

  pkg = require('./package.json');

  path = {
    sourceJs: './source/*.js',
    sourceCss: './source/*.css',
    sourceHtml: './source/*.html',
    dist: './dist',
    build: './build',
    jshint: ['./source/*.js']
  };

  gulp.task('buildJs', function() {
    return gulp.src(path.sourceJs).pipe(uglify()).pipe(gulp.dest(path.build)).pipe(notify({
      message: 'Build Js task complete'
    }));
  });

  gulp.task('distJs', function() {
    return gulp.src(path.sourceJs).pipe(concat('script.min.js')).pipe(uglify()).pipe(gulp.dest(path.dist)).pipe(notify({
      message: 'Dist Js complete'
    }));
  });

  gulp.task('buildCss', function() {
    return gulp.src(path.sourceCss).pipe(minifyCss()).pipe(gulp.dest(path.build)).pipe(notify({
      message: 'Css - tarea completada'
    }));
  });

  gulp.task('distCss', function() {
    return gulp.src(path.sourceCss).pipe(concat('styles.min.css')).pipe(minifyCss()).pipe(gulp.dest(path.dist)).pipe(notify({
      message: 'Css - tarea completada'
    }));
  });

  gulp.task('buildHtml', function() {
    return gulp.src(path.sourceHtml).pipe(minifyHtml()).pipe(gulp.dest(path.dist)).pipe(gulp.dest(path.build)).pipe(notify({
      message: 'HTML - tarea completada'
    }));
  });

  gulp.task("validateJs", function() {
    return gulp.src(path.jshint).pipe(jshint()).pipe(jshint.reporter('default')).pipe(notify({
      message: 'JSHints task complete'
    }));
  });

  gulp.task('default', ['buildJs', 'distJs', 'buildCss', 'distCss', 'buildHtml']);

}).call(this);
